# storage settings
recordings_storage: /data/recordings
resources_folder: resources # relative path from recordings_storage to folder with resources like map.html, video, etc.

# database settings
database_type: json # type of database, can be json (TinyDB), mongodb, elasticsearch
database_uri: resources/recordings_example.json # URL for elasticsearch, mongodb or path to .json for TinyDB
database_name: bagman # used as db_name/collection in mongodb or index in elasticsearch
database_columns: ['name', 'path', 'start_time', 'end_time', 'duration', 'description', 'operator', 'vehicle', 'location', 'size', 'files', 'topics', 'time_added', 'time_modified'] # columns which are mandatory in database
database_sort_by: 'start_time' # column to sort recordings by in the dashboard, leave empty to disable sorting

# recorder settings
metadata_recorder: ['name', 'description', 'operator', 'vehicle', 'location'] # fields which needs to be set manually since cannot be extracted from .mcap
metadata_file: bagman.yaml
metadata_use_header_stamp: False # use ROS header stamp instead of log time from .mcap (this increases processing time since messages need to be decoded)

# dashboard settings
dashboard_port: 8502
dash_name: bagman
dash_icon: '🛍️'
dash_logo: resources/bagman_logo.png # path to logo file
dash_cols_mandatory: [] # colums which will always be displayed
dash_cols_ignore: ['files', 'topics'] # these columns will be deleted from the dataframe
dash_cols_default: ['start_time', 'name', 'duration', 'description', 'path'] # columns which are displayed by default, others can be selected
dash_cols_no_filter: ['name', 'path', 'description'] # columns which cannot be filtered
dash_cols_datetime: ['start_time', 'end_time', 'time_added', 'time_modified'] # columns which are of type datetime
dash_cols_timedelta: ['duration'] # columns which are of type timedelta
dash_max_categories: 10 # max unique values for a column to apply categorial filter
dash_upload_files: #['mcap', 'json', 'yaml', 'txt']  list with allowed file types for upload, leave empty for all
dash_allow_path_link: False # allow to open link of path in new tab (e.g. for links starting with ftp://)
# dash_timezone: UTC # specify the timezone to convert datetime columns to (e.g., UTC, Europe/Zurich, America/Los_Angeles). Leave commented to use the system's local timezone.
