version: '3.3'

services:
  bagman:
    image: bagman
    ports:
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
    volumes:
      - ${RECORDINGS_STORAGE}:${RECORDINGS_STORAGE}
    environment:
      - DASHBOARD_PORT=${DASHBOARD_PORT}
