[server]
maxUploadSize = 4096

[browser]
gatherUsageStats = false

[client]
toolbarMode = "developer"

[theme]
primaryColor = "#00DB84"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
